########
# Core #
###############################################################################

##########
# Stages #
###############################################################################
stages:
  - docker_image
  - doc
  - build
  - test

################
# Docker image #
###############################################################################
docker_image:
  stage: docker_image
  image: docker:latest

  services:
    - docker:dind

  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/toolchain:$CI_BUILD_REF_NAME toolchain/
    - docker push $CI_REGISTRY_IMAGE/toolchain:$CI_BUILD_REF_NAME

########
# Build #
###############################################################################
build:
  image: $CI_REGISTRY/cyberegoorg/cetech/toolchain:master
  stage: build

  variables:
    GIT_SUBMODULE_STRATEGY: normal

  artifacts:
    paths:
      - bin

  script:
    - python3 scripts/build.py




########
# Test #
###############################################################################
#test:
#  image: $CI_REGISTRY/cyberegoorg/cetech-docker-toolchain:master
#  stage: test
#  variables:
#    SDL_VIDEODRIVER: dummy
#
#  dependencies:
#    - build
#
#  script:
#    - py.test -v --color=yes engine/test

#################
# Gitlab pages  #
###############################################################################
pages:
  image: $CI_REGISTRY/cyberegoorg/cetech/toolchain:master
  stage: doc
  script:
    - cp -R docs public
    - cp docs/index.md.html public/index.html

  only:
    - master

  artifacts:
    paths:
      - public
